version: '3.8'

services:
  backend:
    build: .
    container_name: backend-django
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENV: production
      DEFAULT_DB_HOST: postgresdb
      DEFAULT_DB_NAME: postgres
      DEFAULT_DB_USER: postgres
      DEFAULT_DB_PASSWD: postgres

  postgresdb:
    build: ./postgresql
    container_name: postgres-db
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: hello
