version: '3.8'

services:
  postgresdb:
    build: ./postgresql
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}

  redis:
    build: ./redis
    ports:
      - "127.0.0.1:6379:6379"

  backend:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DJANGO_ENV:${DJANGO_ENV}
      - SECRET_KEY:${SECRET_KEY}
      - POSTGRES_NAME:${POSTGRES_NAME}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - KAVENEGAR_API:${KAVENEGAR_API}
