version: '3.8'

services:
  postgresdb:
    build: ./postgresql
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.production

  redis:
    build: ./redis
    ports:
      - "127.0.0.1:6379:6379"

  backend:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DJANGO_ENV: production
    env_file:
      - ./envs/.env.production
